language: php

php:
    - 5.3
    - 5.5

install: composer require

script:
    - find app/ -type f -regex '.*\.php\|.*\.php\.j2' -exec php -lf {} \; | grep "Errors parsing ";
    - vendor/bin/phpunit test