build: false
shallow_clone: true
platform:
    - x86
    - x64
clone_folder: c:\projects\mapguide-rest
branches:
    only:
      - master

init:
    - SET PATH=c:\php_%PLATFORM%;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1

install:
    - IF EXIST c:\php_%PLATFORM% (SET PHP=0) ELSE (mkdir c:\php_%PLATFORM%)
    - cd c:\php_%PLATFORM%
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.5.17-nts-Win32-VC11-%PLATFORM%.zip
    - IF %PHP%==1 7z x php-5.5.17-nts-Win32-VC11-%PLATFORM%.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_gd2.dll >> php.ini
    - IF %PHP%==1 echo extension=php_xsl.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\mapguide-rest
    - composer install --prefer-source --no-progress --ansi
test_script:
    - vendor\bin\parallel-lint.bat -s -e php,phpt --exclude vendor .
    - vendor\bin\phpunit test